# Generated by Django 5.2.1 on 2025-05-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecord',
            name='end_at',
            field=models.TimeField(blank=True, default='10:00', null=True),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='start_at',
            field=models.TimeField(blank=True, default='10:00', null=True),
        ),
    ]
