# Generated by Django 5.2.1 on 2025-05-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_customerrecord_end_at_customerrecord_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='job_title',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
