# Generated by Django 5.2.1 on 2025-05-31 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_doctor_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image_profile',
        ),
    ]
