# Generated by Django 5.2.1 on 2025-05-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_doctor_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='departament',
            new_name='department',
        ),
    ]
