# Generated by Django 5.2.1 on 2025-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_remove_doctor_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='doctor_img/'),
        ),
    ]
