# Generated by Django 5.2.1 on 2025-05-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_rename_departament_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecord',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
