# Generated by Django 5.2.1 on 2025-06-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_alter_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyrecord',
            name='departament',
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_history', to='reception.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_doctor', to='reception.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='doctor_img/'),
        ),
    ]
