# Generated by Django 5.2.1 on 2025-05-18 11:11

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAdmin',
            fields=[
                ('doctor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doctor.doctor')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG')),
                ('job_title', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            bases=('doctor.doctor',),
        ),
        migrations.CreateModel(
            name='AppointmentAdmin',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doctor.appointment')),
                ('payment', models.CharField(choices=[('наличные', 'Наличные'), ('безналичные(карта)', 'Безналичные(карта)')], default='наличные', max_length=33)),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('start_at', models.TimeField(default='10:00')),
                ('end_at', models.TimeField(default='10:00')),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_admin', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('doctor.appointment',),
        ),
    ]
