# Generated by Django 5.2.1 on 2025-05-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoradmin',
            name='doctor_ptr',
        ),
        migrations.DeleteModel(
            name='AppointmentAdmin',
        ),
        migrations.DeleteModel(
            name='DoctorAdmin',
        ),
    ]
