# Generated by Django 5.2.1 on 2025-05-18 12:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_at',
            field=models.TimeField(blank=True, default='10:00', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.CharField(blank=True, choices=[('наличные', 'Наличные'), ('безналичные(карта)', 'Безналичные(карта)')], default='наличные', max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrar_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_at',
            field=models.TimeField(blank=True, default='10:00', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='job_title',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG'),
        ),
    ]
