# Generated by Django 5.2.1 on 2025-05-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='registrar',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
