# Generated by Django 5.2.1 on 2025-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_appointment_discount_appointment_end_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
