# Generated by Django 5.2.1 on 2025-05-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_appointment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.appointment'),
        ),
    ]
