# Generated by Django 5.2.1 on 2025-05-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctorschedule_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='today',
            field=models.DateField(null=True),
        ),
    ]
