# Generated by Django 5.2.1 on 2025-05-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctorschedule_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='today',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
